<?php
/*
 * ErrorResponseHeader
 */
namespace \Models;

/*
 * ErrorResponseHeader
 */
class ErrorResponseHeader {
    /* @var string $requestIdentifier Unique identifier for a call generated by Expedia. */
    private $requestIdentifier;
/* @var int $processingMilliseconds How long the command took to process. */
    private $processingMilliseconds;
/* @var string $errorType Valid values depend on the endpoint. */
    private $errorType;
/* @var string $errorMessage Provides additional information on the error to aid with troubleshooting and resolution. */
    private $errorMessage;
}
