<?php
/*
 * ResponseHeader
 */
namespace \Models;

/*
 * ResponseHeader
 */
class ResponseHeader {
    /* @var string $requestIdentifier Unique identifier for a call generated by Expedia. */
    private $requestIdentifier;
/* @var int $processingMilliseconds How long the command took to process. */
    private $processingMilliseconds;
}
